mode: raw_to_bert  # 'df', 'train_bert', 'test_bert'
datasets_main_dir: datasets
train_split_frac: 1.0
n_cpus: 2
model_name: monologg/kobert
tgt_type: str_list

defaults:
  - dataset: sample

dirs:
  df: df
  json: json
  bert: bert
  log_file: data_prepro.log

hydra:
  run:
    dir: ./${datasets_main_dir}/${dataset_name}
  output_subdir: null # ${now:%Y-%m-%d}/${now:%H-%M-%S}
